package com.chunmi.vote.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import com.chunmi.vote.po.VoteActive;
import com.chunmi.vote.utils.PageRequest;

@Mapper
public interface VoteActiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_active
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_active
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int insert(VoteActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_active
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int insertSelective(VoteActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_active
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    VoteActive selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_active
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int updateByPrimaryKeySelective(VoteActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_active
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int updateByPrimaryKey(VoteActive record);

    @Select("select count(1) from cm_vote_active where del_flag = '0'")
	Long selectVoteActiveCounts();

    
    
    @Select("select * from cm_vote_active where del_flag = '0' order by create_time desc limit #{pageRequest.page},#{pageRequest.pageSize}")
	List<VoteActive> selectActiveListByPage(@Param("pageRequest")PageRequest pageRequest);

    
    @Select("select * from cm_vote_active where del_flag = '0'")
	List<VoteActive> selectVoteActiveList();

    
    @Update("update cm_vote_active set is_start=#{isStart} where id=#{id} and del_flag = '0'")
	Integer updateActiveStatus(VoteActive active);

    @Select("select * from cm_vote_active where del_flag = '0' and is_start='1'")
	List<VoteActive> selectVoteActiveListWithStart();

	Integer updateActiveStatusByNowTime(@Param("nowTime")String nowTime);

	@Update("update cm_vote_active set del_flag='1' where id=#{activeId}")
	Integer delActiveById(@Param("activeId") Long activeId);
}