package com.chunmi.vote.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import com.chunmi.vote.po.VoteGroup;

@Mapper
public interface VoteGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_group
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_group
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int insert(VoteGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_group
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int insertSelective(VoteGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_group
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    VoteGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_group
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int updateByPrimaryKeySelective(VoteGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_group
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int updateByPrimaryKey(VoteGroup record);

    /**
     * 查询所有分组
     * @return
     */
    @Select("select * from cm_vote_group where del_flag = '0'")
	List<VoteGroup> selectVoteGroupList();
}