package com.chunmi.vote.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import com.chunmi.vote.po.VoteRole;

@Mapper
public interface VoteRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_role
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_role
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int insert(VoteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_role
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int insertSelective(VoteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_role
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    VoteRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_role
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int updateByPrimaryKeySelective(VoteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_role
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    int updateByPrimaryKey(VoteRole record);
    
    @Select("select * from cm_vote_role where del_flag = '0'")
	List<VoteRole> selectVoteRoleList();
}