package com.chunmi.vote.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.chunmi.vote.po.VoteRecord;

@Mapper
public interface VoteRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_record
     *
     * @mbg.generated Tue Nov 21 15:55:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_record
     *
     * @mbg.generated Tue Nov 21 15:55:04 CST 2017
     */
    int insert(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_record
     *
     * @mbg.generated Tue Nov 21 15:55:04 CST 2017
     */
    int insertSelective(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_record
     *
     * @mbg.generated Tue Nov 21 15:55:04 CST 2017
     */
    VoteRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_record
     *
     * @mbg.generated Tue Nov 21 15:55:04 CST 2017
     */
    int updateByPrimaryKeySelective(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_vote_record
     *
     * @mbg.generated Tue Nov 21 15:55:04 CST 2017
     */
    int updateByPrimaryKey(VoteRecord record);

    
    @Select("select count(1) from cm_vote_record where del_flag = '0' and active_id=#{activeId} and vote_group_id = #{voteGroupId}")
	Long selectLimitVoteCounts(VoteRecord voteRecord);

    
    
    @Update("update cm_vote_record set del_flag = '1',del_time=NOW() where be_voted_production_id = #{productionId}")
	Integer delVoteRecordByProductionId(@Param("productionId")Long productionId);
}