# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://39.108.239.226:3306/cm_vote?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.jdbc.Driver