package com.chunmi.vote.po;

import java.util.Date;

import org.springframework.stereotype.Component;

@Component
public class VoteUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.user_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.user_nickname
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.user_password
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.head_pic
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String headPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.group_id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.role_id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_users.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String delFlag;
    
    
    /**
     * 所属分组
     */
    private VoteGroup voteGroup;
    
    
    /**
     * 用户角色
     */
    private VoteRole voteRole;

    public VoteGroup getVoteGroup() {
		return voteGroup;
	}

	public void setVoteGroup(VoteGroup voteGroup) {
		this.voteGroup = voteGroup;
	}

	public VoteRole getVoteRole() {
		return voteRole;
	}

	public void setVoteRole(VoteRole voteRole) {
		this.voteRole = voteRole;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.id
     *
     * @return the value of cm_vote_users.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.id
     *
     * @param id the value for cm_vote_users.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.user_name
     *
     * @return the value of cm_vote_users.user_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.user_name
     *
     * @param userName the value for cm_vote_users.user_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.user_nickname
     *
     * @return the value of cm_vote_users.user_nickname
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.user_nickname
     *
     * @param userNickname the value for cm_vote_users.user_nickname
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.user_password
     *
     * @return the value of cm_vote_users.user_password
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.user_password
     *
     * @param userPassword the value for cm_vote_users.user_password
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.head_pic
     *
     * @return the value of cm_vote_users.head_pic
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.head_pic
     *
     * @param headPic the value for cm_vote_users.head_pic
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.group_id
     *
     * @return the value of cm_vote_users.group_id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.group_id
     *
     * @param groupId the value for cm_vote_users.group_id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.role_id
     *
     * @return the value of cm_vote_users.role_id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.role_id
     *
     * @param roleId the value for cm_vote_users.role_id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.create_time
     *
     * @return the value of cm_vote_users.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.create_time
     *
     * @param createTime the value for cm_vote_users.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.update_time
     *
     * @return the value of cm_vote_users.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.update_time
     *
     * @param updateTime the value for cm_vote_users.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_users.del_flag
     *
     * @return the value of cm_vote_users.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_users.del_flag
     *
     * @param delFlag the value for cm_vote_users.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}