package com.chunmi.vote.po;

import java.util.Date;
import java.util.List;

public class VoteActive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.active_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String activeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.is_start
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String isStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.start_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.end_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_active.remark
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String remark;
    
    /**
     * 作品列表
     */
    private List<VoteProduction> voteProductionList; 
    
    
   /**
    * 开始时间(格式化字符串)
    */
    private String startTimeStr;
    
    
    /**
     * 结束时间(格式化字符串)
     */
    private String endTimeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.id
     *
     * @return the value of cm_vote_active.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.id
     *
     * @param id the value for cm_vote_active.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.active_name
     *
     * @return the value of cm_vote_active.active_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getActiveName() {
        return activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.active_name
     *
     * @param activeName the value for cm_vote_active.active_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setActiveName(String activeName) {
        this.activeName = activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.is_start
     *
     * @return the value of cm_vote_active.is_start
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getIsStart() {
        return isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.is_start
     *
     * @param isStart the value for cm_vote_active.is_start
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setIsStart(String isStart) {
        this.isStart = isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.start_time
     *
     * @return the value of cm_vote_active.start_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.start_time
     *
     * @param startTime the value for cm_vote_active.start_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.end_time
     *
     * @return the value of cm_vote_active.end_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.end_time
     *
     * @param endTime the value for cm_vote_active.end_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.create_time
     *
     * @return the value of cm_vote_active.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.create_time
     *
     * @param createTime the value for cm_vote_active.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.update_time
     *
     * @return the value of cm_vote_active.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.update_time
     *
     * @param updateTime the value for cm_vote_active.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.del_time
     *
     * @return the value of cm_vote_active.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.del_time
     *
     * @param delTime the value for cm_vote_active.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.del_flag
     *
     * @return the value of cm_vote_active.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.del_flag
     *
     * @param delFlag the value for cm_vote_active.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_active.remark
     *
     * @return the value of cm_vote_active.remark
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_active.remark
     *
     * @param remark the value for cm_vote_active.remark
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public List<VoteProduction> getVoteProductionList() {
		return voteProductionList;
	}

	public void setVoteProductionList(List<VoteProduction> voteProductionList) {
		this.voteProductionList = voteProductionList;
	}

	public String getStartTimeStr() {
		return startTimeStr;
	}

	public void setStartTimeStr(String startTimeStr) {
		this.startTimeStr = startTimeStr;
	}

	public String getEndTimeStr() {
		return endTimeStr;
	}

	public void setEndTimeStr(String endTimeStr) {
		this.endTimeStr = endTimeStr;
	}
    
    
    
}