package com.chunmi.vote.po;

import java.util.Date;

public class VoteRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_role.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_role.role_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_role.role_type
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_role.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_role.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_role.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_role.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_role.id
     *
     * @return the value of cm_vote_role.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_role.id
     *
     * @param id the value for cm_vote_role.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_role.role_name
     *
     * @return the value of cm_vote_role.role_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_role.role_name
     *
     * @param roleName the value for cm_vote_role.role_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_role.role_type
     *
     * @return the value of cm_vote_role.role_type
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_role.role_type
     *
     * @param roleType the value for cm_vote_role.role_type
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_role.create_time
     *
     * @return the value of cm_vote_role.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_role.create_time
     *
     * @param createTime the value for cm_vote_role.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_role.update_time
     *
     * @return the value of cm_vote_role.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_role.update_time
     *
     * @param updateTime the value for cm_vote_role.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_role.del_time
     *
     * @return the value of cm_vote_role.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_role.del_time
     *
     * @param delTime the value for cm_vote_role.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_role.del_flag
     *
     * @return the value of cm_vote_role.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_role.del_flag
     *
     * @param delFlag the value for cm_vote_role.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}