package com.chunmi.vote.po;

import java.util.Date;

public class VoteGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_group.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_group.group_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_group.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_group.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_group.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private Date delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vote_group.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_group.id
     *
     * @return the value of cm_vote_group.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_group.id
     *
     * @param id the value for cm_vote_group.id
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_group.group_name
     *
     * @return the value of cm_vote_group.group_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_group.group_name
     *
     * @param groupName the value for cm_vote_group.group_name
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_group.create_time
     *
     * @return the value of cm_vote_group.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_group.create_time
     *
     * @param createTime the value for cm_vote_group.create_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_group.update_time
     *
     * @return the value of cm_vote_group.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_group.update_time
     *
     * @param updateTime the value for cm_vote_group.update_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_group.del_time
     *
     * @return the value of cm_vote_group.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_group.del_time
     *
     * @param delTime the value for cm_vote_group.del_time
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vote_group.del_flag
     *
     * @return the value of cm_vote_group.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vote_group.del_flag
     *
     * @param delFlag the value for cm_vote_group.del_flag
     *
     * @mbg.generated Thu Nov 09 16:15:05 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}